models:
  - type: main
    engine: openai
    model: deepseek-chat  # 也可以是 deepseek-reasoner (R1)
    parameters:
      openai_api_base: "https://api.deepseek.com"


# Instructions for the LLM (similar to system prompts)
#instructions:
#  - type: general
#    content: |
#      You are a helpful AI assistant.

# Guardrails configuration
rails:
  input:
    flows:
      - check input safety azure
      #- check input safety 
  output:
    flows:
      - check output safety cat

# Prompt customization
#prompts:
#  - task: self_check_input
#    content: |
#      Your task is to check if the user message complies with policy.

# Knowledge base settings
knowledge_base:
  embedding_search_provider:
    name: default

# Tracing and monitoring
tracing:
  enabled: true
  adapters:
    - name: FileSystem
      filepath: "./logs/traces.jsonl"